[build]
  command = "pnpm install --shamefully-hoist && pnpm run build"
  publish = ".next"

[context.production.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[functions]
  directory = "netlify/functions"